= CSM Docker: SLE Python
:toc:
:toclevels: 3

A SLE Server Python Docker image used for RPM builds.

== Available Images

See a list of available Python Images with `git tag`, but in general there are:

.Stable Docker Tags
[options="header",cols="m,1*^,m"]
|===
| Docker Tag | Base OS | GLIBC

| 3.10
| SLES-15-SP4
| 2.31

| 3.9
| SLES-15-SP3
| 2.31

| 3.6
| SLES-15-SP2
| 2.26
|===

Tags can also be seen directly at https://artifactory.algol60.net/artifactory/csm-docker/stable/csm-docker-sle-python.

== Usage

The provided `Makefile` adds Jenkins Pipeline variables to the `docker build` command.
The commands below are for use outside of the CSM Jenkins Pipeline.

[source,bash]
----
export DOCKER_BUILDKIT=1
export SLES_REGISTRATION_CODE=<registration_code>

make image

docker run -it csm-docker-sle-python:3.6
----

=== Remote Usage

To use the images built from Jenkins, use the full URL:

[source,bash]
----
docker run -it artifactory.algol60.net/csm-docker/stable/csm-docker-sle-python:3.6 bash

# Git Hash
docker run -it artifactory.algol60.net/csm-docker/stable/csm-docker-sle-python:3.6-<hash> bash
----

== Python Version(s)

The version is controlled by the `Jenkinsfile`.

Unstable image tags will publish using these tags:

* `[MAJOR.MINOR]-[HASH]`
* `[MAJOR.MINOR]-[HASH]-[TIMESTAMP]`

Stable image tags will publish using these tags:

* `[MAJOR.MINOR]`
* `[MAJOR.MINOR]-[HASH]`
* `[MAJOR.MINOR]-[HASH]-[TIMESTAMP]`

=== Updating Python

To use a newer version of GoLang, update the `Jenkinsfile` with a new `pythonVersion`.