= CSM Docker: SLE Python

A SLE Server Python Docker image used for RPM builds.

== Available Images

See a list of available Python Images with `git tag`, but in general there are:

* `3.10`, and `3.10.4`
* `3.8` and `3.8.13`
* `3.6` and `3.6.15`
* `3.6_leap15.2` and `3.6.15_leap15.2`

Tags can also be seen directly at https://artifactory.algol60.net/artifactory/csm-docker/stable/csm-docker-sle-python.

== Building

The provided `Makefile` adds Jenkins Pipeline variables to the `docker build` command. The commands below are for use outside of the CSM Jenkins Pipeline.

[source,bash]
----
export DOCKER_BUILDKIT=1
export SLES_REGISTRATION_CODE=<registration_code>

# Build Python 3.8.13
docker build --secret id=SLES_REGISTRATION_CODE --build-arg PY_FULL_VERSION=3.10.4 .

----

== Running

[source,bash]
----
# Python Major Minor Version
docker run -it artifactory.algol60.net/csm-docker/stable/csm-docker-sle-python:3.8

# Python Version
docker run -it artifactory.algol60.net/csm-docker/stable/csm-docker-sle-python:3.8.13

# Git Hash
docker run -it artifactory.algol60.net/csm-docker/stable/csm-docker-sle-python:<hash>
----

== Python Version(s)

The version is controlled by the `Jenkinsfile`.

Unstable image tags will publish using these tags:

* `[HASH]`
* `[HASH]-[TIMESTAMP]`

Stable image tags will publish using these tags:

* `[MAJOR.MINOR]`
* `[MAJOR.MINOR.PATCH]`
* `[MAJOR.MINOR.PATCH]-[HASH]`
* `[MAJOR.MINOR.PATCH]-[HASH]-[TIMESTAMP]`

=== Updating Python

To use a newer version of GoLang, update the `Jenkinsfile` with a new `pythonVersion`.