= CSM Docker: SLE Python

A SLE Server Python Docker image used for RPM builds.

Available images can only be seen by querying the Docker API or
https://artifactory.algol60.net/artifactory/csm-docker/stable/csm-docker-sle-python[visiting the registry itself].

== Building

The provided `Makefile` adds Jenkins Pipeline variables to the `docker build` command. The commands below are for use outside of the CSM Jenkins Pipeline.

[source,bash]
----
export DOCKER_BUILDKIT=1
export SLES_REGISTRATION_CODE=<registration_code>

# Build Python 3.10.8
docker build --secret id=SLES_REGISTRATION_CODE --build-arg PY_VERSION=3.10 .
----

== Running

[source,bash]
----
# Python version (major.minor)
docker run -it artifactory.algol60.net/csm-docker/stable/csm-docker-sle-python:3.10

# Python version (major.minor.bugfix) and distro
docker run -it artifactory.algol60.net/csm-docker/stable/csm-docker-sle-python:3.10-SLES15.4
----

== Python Version(s)

The version is controlled by the `Jenkinsfile`.

Unstable image tags will publish using these tags:

* `[DISTRO]-[HASH]`
* `[DISTRO]-[HASH]-[TIMESTAMP]`

Stable image tags will publish using these tags:

.The `[MAJOR.MINOR]` image is only created against the latest distro.
* `[MAJOR.MINOR]`
* `[MAJOR.MINOR]-[HASH]`
* `[MAJOR.MINOR]-[HASH]-[TIMESTAMP]`
* `[MAJOR.MINOR]-[DISTRO]`
* `[MAJOR.MINOR]-[DISTRO]-[HASH]`
* `[MAJOR.MINOR]-[DISTRO]-[HASH]-[TIMESTAMP]`

=== Updating Python

To use a newer version of GoLang, update the `Jenkinsfile` with a new `pythonVersion`.